import 'package:equatable/equatable.dart';
import 'today_mode.dart';

/// Indicates the severity level of missed tasks.
enum RecoverySeverity {
  light,
  moderate,
  heavy,
}

/// Represents the recommendation generated by the engine.
class RecoveryRecommendation extends Equatable {
  const RecoveryRecommendation({
    required this.severity,
    required this.title,
    required this.message,
    required this.recommendedMode,
    required this.suggestDeferMemorization,
    required this.suggestResolveMissedWork,
    required this.steps,
  });

  final RecoverySeverity severity;
  final String title;
  final String message;
  final TodayMode recommendedMode;
  final bool suggestDeferMemorization;
  final bool suggestResolveMissedWork;
  final List<String> steps;

  @override
  List<Object?> get props => [
        severity,
        title,
        message,
        recommendedMode,
        suggestDeferMemorization,
        suggestResolveMissedWork,
        steps,
      ];
}
