// Mocks generated by Mockito 5.4.6 from annotations
// in itqan/test/features/today/application/old_review_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:itqan/features/progress/data/segment_progress_repository.dart'
    as _i2;
import 'package:itqan/features/progress/domain/quran_segment_progress.dart'
    as _i4;
import 'package:itqan/features/progress/domain/segment_progress_source.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SegmentProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSegmentProgressRepository extends _i1.Mock
    implements _i2.SegmentProgressRepository {
  MockSegmentProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertSegmentProgress(_i4.QuranSegmentProgress? segment) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertSegmentProgress,
          [segment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.QuranSegmentProgress?> getSegmentProgressForRange(
    String? planId,
    int? startSurah,
    int? startAyah,
    int? endSurah,
    int? endAyah,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSegmentProgressForRange,
          [
            planId,
            startSurah,
            startAyah,
            endSurah,
            endAyah,
          ],
        ),
        returnValue: _i3.Future<_i4.QuranSegmentProgress?>.value(),
      ) as _i3.Future<_i4.QuranSegmentProgress?>);

  @override
  _i3.Future<_i4.QuranSegmentProgress?> getSegmentProgressById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSegmentProgressById,
          [id],
        ),
        returnValue: _i3.Future<_i4.QuranSegmentProgress?>.value(),
      ) as _i3.Future<_i4.QuranSegmentProgress?>);

  @override
  _i3.Future<List<_i4.QuranSegmentProgress>> getDueSegmentsForPlan({
    required String? planId,
    required DateTime? date,
    _i5.SegmentProgressSource? source,
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDueSegmentsForPlan,
          [],
          {
            #planId: planId,
            #date: date,
            #source: source,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i4.QuranSegmentProgress>>.value(
            <_i4.QuranSegmentProgress>[]),
      ) as _i3.Future<List<_i4.QuranSegmentProgress>>);
}
