// Mocks generated by Mockito 5.4.6 from annotations
// in itqan/test/features/today/application/today_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:itqan/features/today/application/near_review_service.dart'
    as _i3;
import 'package:itqan/features/today/application/old_review_service.dart'
    as _i6;
import 'package:itqan/features/today/application/recovery_service.dart' as _i7;
import 'package:itqan/features/today/data/recovery_resolution_repository.dart'
    as _i10;
import 'package:itqan/features/today/data/today_adjustment_repository.dart'
    as _i9;
import 'package:itqan/features/today/domain/recovery_notice.dart' as _i8;
import 'package:itqan/features/today/domain/recovery_resolution.dart' as _i11;
import 'package:itqan/features/today/domain/today_adjustment.dart' as _i2;
import 'package:itqan/features/today/domain/today_task.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodayAdjustment_0 extends _i1.SmartFake
    implements _i2.TodayAdjustment {
  _FakeTodayAdjustment_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NearReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearReviewService extends _i1.Mock implements _i3.NearReviewService {
  MockNearReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TodayTask>> getNearReviewTasks({
    required String? planId,
    int? limit = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearReviewTasks,
          [],
          {
            #planId: planId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.TodayTask>>.value(<_i5.TodayTask>[]),
      ) as _i4.Future<List<_i5.TodayTask>>);
}

/// A class which mocks [OldReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOldReviewService extends _i1.Mock implements _i6.OldReviewService {
  MockOldReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TodayTask>> getOldReviewTasks({
    required String? planId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOldReviewTasks,
          [],
          {
            #planId: planId,
            #date: date,
          },
        ),
        returnValue: _i4.Future<List<_i5.TodayTask>>.value(<_i5.TodayTask>[]),
      ) as _i4.Future<List<_i5.TodayTask>>);
}

/// A class which mocks [RecoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecoveryService extends _i1.Mock implements _i7.RecoveryService {
  MockRecoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.RecoveryNotice?> getRecoveryNotice(
          {required String? planId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryNotice,
          [],
          {#planId: planId},
        ),
        returnValue: _i4.Future<_i8.RecoveryNotice?>.value(),
      ) as _i4.Future<_i8.RecoveryNotice?>);
}

/// A class which mocks [TodayAdjustmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodayAdjustmentRepository extends _i1.Mock
    implements _i9.TodayAdjustmentRepository {
  MockTodayAdjustmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TodayAdjustment> getAdjustment({
    required String? planId,
    required String? dateKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdjustment,
          [],
          {
            #planId: planId,
            #dateKey: dateKey,
          },
        ),
        returnValue:
            _i4.Future<_i2.TodayAdjustment>.value(_FakeTodayAdjustment_0(
          this,
          Invocation.method(
            #getAdjustment,
            [],
            {
              #planId: planId,
              #dateKey: dateKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.TodayAdjustment>);

  @override
  _i4.Future<void> setDeferMemorization({
    required String? planId,
    required String? dateKey,
    required bool? defer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDeferMemorization,
          [],
          {
            #planId: planId,
            #dateKey: dateKey,
            #defer: defer,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [RecoveryResolutionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecoveryResolutionRepository extends _i1.Mock
    implements _i10.RecoveryResolutionRepository {
  MockRecoveryResolutionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.RecoveryResolution?> getResolution(
          {required String? planId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResolution,
          [],
          {#planId: planId},
        ),
        returnValue: _i4.Future<_i11.RecoveryResolution?>.value(),
      ) as _i4.Future<_i11.RecoveryResolution?>);

  @override
  _i4.Future<void> resolveMissedWorkBefore({
    required String? planId,
    required String? resolvedBeforeDateKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveMissedWorkBefore,
          [],
          {
            #planId: planId,
            #resolvedBeforeDateKey: resolvedBeforeDateKey,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
